image: maven:3.3-jdk-8-alpine

cache:
  key: "$CI_PROJECT_NAMESPACE $CI_PROJECT_NAME"
  paths:
    - .m2/

variables: 
  MAVEN_OPTS: "-Dmaven.repo.local=.m2" 
  ORACLE_DB: $DB_URL
  ORACLE_USER: $DB_LOGIN
  ORACLE_PASSWORD: $DB_PASSWORD


stages:
  - test
  - build
  - deploy

unit_test:
  stage: test
  script:
    - mvn clean test -Drun.arguments=--spring.datasource.driver-class-name=oracle.jdbc.OracleDriver,--spring.datasource.url="$ORACLE_DB",--spring.datasource.username="$ORACLE_USER",--spring.datasource.password="$ORACLE_PASSWORD"  -B


check_style:
  stage: test
  script:
    - mvn clean checkstyle:check -B

.build: &build_template
  stage: build
  script:
    - mvn package -B

develop_build:
  <<: *build_template
  only:
    - branches
  except:
    - master
  artifacts:
    expire_in: 1 day
    paths:      
      - target/*.jar

master_build:
  <<: *build_template
  only:
    - master
    - tags
  artifacts:
    expire_in: 1 month
    paths:
      - target/*.jar


      
deploy:
  stage: deploy
  image: ruby:latest
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=testeritto --api-key=$HEROKU_API_KEY
  only:
  - dev
