image: maven:3.3-jdk-8-alpine

cache:
  key: "$CI_PROJECT_NAMESPACE $CI_PROJECT_NAME"
  paths:
    - .m2/


stages:
  - test
  - build
  - deploy
  
# variables:
#     ORACLE_URL: $DB_URL
#     ORACLE_PASSWORD: $DB_PASSWORD
#     ORACLE_LOGIN: $DB_LOGIN

unit_test:
  stage: test
  
  script:
    - export ORACLE_URL="$DB_URL"
    - export ORACLE_PASSWORD="$DB_PASSWORD"
    - export ORACLE_LOGIN="$DB_LOGIN"
    - mvn clean test -Drun.arguments=--spring.datasource.url="${ORACLE_URL}",--spring.datasource.username="${ORACLE_LOGIN}",--spring.datasource.password="${ORACLE_PASSWORD}"  -B



check_style:
  stage: test
  script:
    - mvn clean checkstyle:check -B

.build: &build_template
  stage: build
  script:
    - mvn package -B

develop_build:
  <<: *build_template
  only:
    - branches
  except:
    - master
  artifacts:
    expire_in: 1 day
    paths:      
      - target/*.jar

master_build:
  <<: *build_template
  only:
    - master
    - tags
  artifacts:
    expire_in: 1 month
    paths:
      - target/*.jar


      
deploy:
  stage: deploy
  image: ruby:latest
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=testeritto --api-key=$HEROKU_API_KEY
  only:
  - dev
