image: maven:3.3-jdk-8-alpine

cache:
  key: "$CI_PROJECT_NAMESPACE $CI_PROJECT_NAME"
  paths:
    - .m2/


stages:
  - test
  - build
  - deploy
  
# variables:
#     DB_URL: "$DB_URL"
#     DB_LOGIN: "$DB_LOGIN"
#     DB_PASSWORD: "$DB_PASSWORD"

unit_test:
  stage: test
  script:
    # - mvn clean test -B
    - export DB_URL="$DB_URL"
    - export DB_LOGIN="$DB_LOGIN"
    - export DB_PASSWORD="$DB_PASSWORD"
#    - export SSL_PASSWORD="$SSL_PASSWORD"
#    - export SSL_KEY_TYPE="$SSL_KEY_TYPE"
#    - export SSL_KEY_ALIAS="$SSL_KEY_ALIAS"
     - mvn clean test -Drun.arguments=--spring.datasource.driver-class-name="oracle.jdbc.OracleDriver",--spring.datasource.url="$DB_URL",--spring.datasource.username="$DB_LOGIN",--spring.datasource.password="$DB_PASSWORD" -B 
    # , --server.ssl.key-store-password="$SSL_PASSWORD", --server.ssl.keyStoreType="$SSL_KEY_TYPE", --server.ssl.keyAlias="SSL_KEY_ALIAS" -B



check_style:
  stage: test
  script:
    - mvn clean checkstyle:check -B

.build: &build_template
  stage: build
  script:
    - mvn package -B

develop_build:
  <<: *build_template
  only:
    - branches
  except:
    - master
  artifacts:
    expire_in: 1 day
    paths:      
      - target/*.jar

master_build:
  <<: *build_template
  only:
    - master
    - tags
  artifacts:
    expire_in: 1 month
    paths:
      - target/*.jar


      
deploy:
  stage: deploy
  image: ruby:latest
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=testeritto --api-key=$HEROKU_API_KEY
  only:
  - dev
