image: maven:3.3-jdk-8-alpine

cache:
  key: "$CI_PROJECT_NAMESPACE $CI_PROJECT_NAME"
  paths:
    - .m2/

variables: 
  MAVEN_OPTS: "-Dmaven.repo.local=.m2" 

stages:
  - test
  - build
  - deploy

unit_test:
  stage: test
  script:
    - mvn clean test -B

check_style:
  stage: test
  script:
    - mvn clean checkstyle:check -B

.build: &build_template
  stage: build
  script:
    - mvn package -B

develop_build:
  <<: *build_template
  only:
    - branches
  except:
    - master
  artifacts:
    expire_in: 1 day
    paths:      
      - target/*.jar

master_build:
  <<: *build_template
  only:
    - master
    - tags
  artifacts:
    expire_in: 1 month
    paths:
      - target/*.jar
      

heroku:
 stage: deploy
 only:
 - master
 script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/testeritto.git
    - git push -f heroku master
  
